### PR TITLE
Refactor localization configurations & models

### PR DESCRIPTION
**Pull request by hishamco**
This fixes a part of issue #545:

- Rename `GlobalConfiguration.SimpleCultures` to `GlobalConfiguration.Cultures`
- Rid off `SimpleCulture` and replace it with the `Culture` model
- Rid off  `ResourceString` and use `Resource` model
- Move the localization models to `SimplCommerce.Infrastructure.Localization`

### CODE REVIEW

**Comment by thiennn** [comment]
Maybe it's not a good idea to move the Culture and Resource class from Localization module to Infrastructure. I think Infrastructure should not be concerned about data persistent or business domain. 
Actually the Localization should be changed to EfLocalization so that maybe we can have others localization provider.

**Comment by hishamco** [comment]
Agree but if we look closely the `Culture` & `Resources` are core piece for any localization source provider: JSON, Database, PO .. etc. All the implementation details are in localization Module

**Comment by hishamco** [comment]
Further more I did an experiment for `EfRequestCultureProvider` so such this will be in the localization module not the localization infrastructure .. hope you got my point

**Comment by hishamco** [comment]
FYI you can have a look to `OrchardCore` they did something similar [here](https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore/OrchardCore.Localization.Abstractions) they construct a `CultureDictionary` & `CultureDictionaryRecord` as a primitives for localization, but the implementation details is up to the provider creator

**Comment by thiennn** [comment]
ok, I think just move the mapping from attributes [Table("Localization_Culture")] and [Table("Localization_Resource")] to LocalizationCustomModelBuilder would be fine

**Comment by hishamco** [comment]
That's what I wanna asked you about 😄

**Pull request merged**
