### PR TITLE
adde payment list to order details

### PR DESCRIPTION
**Pull request by thiennn**

### CODE REVIEW

**Comment by Joy2BeWith** [comment]
Got latest and updated database - got this error


Internal Server Error An unhandled exception occurred while processing the
request.
InvalidOperationException: Role GUEST does not exist.

Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore+<AddToRoleAsync>d__34.MoveNext()

   - Stack
   - Query
   - Cookies
   - Headers


   - InvalidOperationException: Role GUEST does not exist.
      -
      Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore+<AddToRoleAsync>d__34.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Identity.UserManager+<AddToRoleAsync>d__104.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      - System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      - SimplCommerce.Module.Core.Extensions.WorkContext+<GetCurrentUser>d__7.MoveNext()
      in WorkContext.cs+
      1. FullName = "Guest",
         2. UserGuid = userGuid.Value,
         3. Email = dummyEmail,
         4. UserName = dummyEmail
         5. };
         6. var abc = await _userManager.CreateAsync(_currentUser,
         "1qazZAQ!");
      1. await _userManager.AddToRoleAsync(_currentUser, "guest");
      1. SetUserGuidCookies(_currentUser.UserGuid);
         2. return _currentUser;
         3. }
         4.
         5. private Guid? GetUserGuidFromCookies()
         6. {
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      - System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      - SimplCommerce.Module.ShoppingCart.Components.CartBadgeViewComponent+<InvokeAsync>d__3.MoveNext()
      in CartBadgeViewComponent.cs+
      1. _cartService = cartService;
         2. _workContext = workContext;
         3. }
         4.
         5. public async Task<IViewComponentResult> InvokeAsync()
         6. {
      1. var currentUser = await _workContext.GetCurrentUser();
      1. var cart = await _cartService.GetCart(currentUser.Id);
         2. return
         View("/Modules/SimplCommerce.Module.ShoppingCart/Views/Components/CartBadge.cshtml",
         cart.Items.Count);
         3. }
         4. }
         5. }
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker+<InvokeAsyncCore>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker+<InvokeAsync>d__5.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper+<InvokeCoreAsync>d__12.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      - System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      - AspNetCore._Views_Shared__Layout_cshtml+<<ExecuteAsync>b__29_5>d.MoveNext()
      in _Layout.cshtml+
      1. </a>
         2. </div>
         3. <div class="col-xs-10 col-md-7 search-box">
         4. @await Component.InvokeAsync("SearchForm")
         5. </div>
         6. <div class="col-xs-2 col-md-1 cart-btn">
      1. @await Component.InvokeAsync("CartBadge")
      1. </div>
         2. </div>
         3. </div>
         4. </div>
         5. <div class="navbar navbar-default main-nav">
         6. <div class="container">
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext+<SetOutputContentAsync>d__30.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      AspNetCore._Views_Shared__Layout_cshtml+<ExecuteAsync>d__29.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageCoreAsync>d__16.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageAsync>d__15.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderLayoutAsync>d__18.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderAsync>d__14.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__22.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__21.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext
      context)
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State
      next, ref Scope scope, ref object state, ref bool isCompleted)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext
      context)
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State
      next, ref Scope scope, ref object state, ref bool isCompleted)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by thiennn** [comment]
It seems that the seed data hasn't been imported. Please delete all the user in Core_User table and run the following script https://github.com/simplcommerce/SimplCommerce/blob/master/src/Database/StaticData.sql

**Comment by Joy2BeWith** [comment]
Hi Thien, when i try and add a new logo and publish my new logo gets
removed automatically... what setting can i change to stop this? thanks for
all you do!

**Comment by thiennn** [comment]
Your logo seem be replaced on build by the copy-module. Generally you should modify in Modules not in the Host. 
You should checkout the docs http://docs.simplcommerce.com/en/latest/development-tips/

**Comment by Joy2BeWith** [comment]
Thank you!!

**Comment by Joy2BeWith** [comment]
I’m old school MVC and new to core

**Pull request merged**
