### PR TITLE
#112 migrate project.json to csproj

### PR DESCRIPTION
**Pull request by thiennn**

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
@thiennn Which tooling are using for these migrations?

**Comment by thiennn** [comment]
VS 2017. Worked fine on local but the new sdk haven't been supported on appveyor and travis

**Comment by MaherJendoubi** [comment]
@thiennn which version of VS2017?

**Comment by MaherJendoubi** [comment]
image

**Comment by MaherJendoubi** [comment]
@thiennn please read this blog post very important : https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/

**Comment by thiennn** [comment]
@MaherJendoubi thanks, aready read that and also http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/.
I use the latest version of VS2017 and .NET Core SDK RC4

**Comment by MaherJendoubi** [comment]
@thiennn Excellent :) but you forget this one http://www.natemcmaster.com/blog/2017/02/01/project-json-to-csproj-part2/ ;-)

**Pull request merged**
