### PR TITLE
Fixed issue #102

### PR DESCRIPTION
**Pull request by MaherJendoubi**
* completed Load() method

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
@thiennn Would you please review it for me : I tried to fix issue #102 .

**Comment by MaherJendoubi** [comment]
@rowanmiller Would you please review it for me? Thanks.

**Comment by thiennn** [comment]
I haved tried this. EnsureCreated does not work well with Migration

**Comment by MaherJendoubi** [comment]
@thiennn I followed the docs...

**Comment by MaherJendoubi** [comment]
@ajcvickers Would you please review it for me? Thanks.

**Comment by MaherJendoubi** [comment]
@thiennn I have this issue : 
image

**Comment by thiennn** [comment]
@MaherJendoubi please take a look at the migration history table "__EFMigrationsHistory" to have more clue and you might need to delete table "Core_AppSetting" and run Update-Database again

**Comment by rowanmiller** [comment]
Looks like you created the database using `Database.EnsureCreated()` and are then trying to use migrations. These two are mutually exclusive and can not be combined. You can use `Database.Migrate()` to create the database if you are using migrations.

**Comment by MaherJendoubi** [comment]
@rowanmiller  Thanks! BTW I still having the same issue : 
image

**Comment by rowanmiller** [comment]
You need to do one of the things listed in the error. The easiest one would be to implement IDbContextFactory and create the options to point to your database and pass it to your context constructor.

**Comment by MaherJendoubi** [comment]
@rowanmiller Do you mean this chunck of code?

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace SimplCommerce.Module.Core.Data
{
    public class SimplDbContextFactory : IDbContextFactory<SimplDbContext>
    {
        public SimplDbContext Create(DbContextFactoryOptions options)
        {
            var optionsBuilder = new DbContextOptionsBuilder<SimplDbContext>();
            return new SimplDbContext(optionsBuilder.Options);
        }
    }
}

**Comment by rowanmiller** [comment]
Yes, but you'll need to set the connection to use on the options (`optionsBuilder.UseSqlServer(...)`)

**Comment by MaherJendoubi** [comment]
@rowanmiller 
image

**Comment by rowanmiller** [comment]
I don't have much to add to what the error message says 😄... do that.

**Comment by MaherJendoubi** [comment]
@thiennn Do we need to change the model? Update-Database gives me this error : 
image

**Comment by MaherJendoubi** [comment]
@thiennn The database is not created only migrations:
image

**Comment by thiennn** [comment]
I don't think this approach gona work. It's too early to call Database.Migrate() here in the constructor of Startup.cs. At this stage, all modules haven't been loaded.

As I said earlier, I think we should found a way to skip adding this ef configuration provider if the application is invoked by the EF CLI like add-migration command.

```cs
if(!invokedByEfCLI) {
           builder.AddEntityFrameworkConfig(options =>
                options.UseSqlServer(connectionStringConfig.GetConnectionString("DefaultConnection"))
            );
}
```

I have asked a question here https://github.com/aspnet/EntityFramework/issues/7387.

**Comment by thiennn** [comment]
fixed in #198

**Pull request closed without merging**
