### PR TITLE
#19 Category tree with checkbox in product form

### PR DESCRIPTION
**Pull request by arst**
1. Mark parent categories when child category marked
2. Unmark child categories when parent category unmarked

### CODE REVIEW

**Comment by thiennn** [comment]
@arst  thank  you very much for the effort, just one wondering can we use the array.find() instead of writing getCategoriesByProperty() function?

**Comment by arst** [comment]
Hi @thiennn, thanks for the review. Array.prototype.find isn't supported by  Internet Explorer. So we should whether use some polifyll or drop support for IE to actually use it in code. Btw, product-selection-directive uses Array.prototype.find so we have a lot of exceptions in product form when it is opened in IE.

**Comment by thiennn** [comment]
The administration pages are used only by a few of peoples, and we won't support IE for the back-office

**Comment by arst** [comment]
@thiennn Redundant functions were eliminated

**Pull request merged**
