### PR TITLE
Initial product recommendation engine

### PR DESCRIPTION
**Pull request by ainhattv**

### CODE REVIEW

**Comment by afernandes** [comment]
I don't know much about machine learning, but how is it possible to use the ID of Amazon products to recommend simplCommerce IDs that are totally different.
Should the barcode be used?
or some other code in common, for example GTIN?

**Comment by hishamco** [comment]
This is HUGE, first time I see ML in action here, thanks @ainhattv for the PR I will have a deep look into the code, but is there an online demo to test this feature or you can arrange with @thiennn for that if it's possible

**Comment by ainhattv** [comment]
In the current, this is solution cannot release because that was builded on Amazon example Dataset. The ML learning solution should be build on real data of the system. The data is most important with ML feature, so i will improve this solution for long time running.

**Comment by hishamco** [comment]
> In the current, this is solution cannot release because that was builded on Amazon example Dataset

I see, for simplicity we can suggest the products that have some similarities with the displayed one, for example product name, description, tags .. etc

**Comment by thiennn** [comment]
Hi @ainhattv  thank you for your nice work. But I think the code is more for reference. It is not some thing we can put in production. So I cannot merge to the code base but will keep here for reference purpose. 

I also have some comments on the code

**Comment by ainhattv** [comment]
Hi A. @thiennn,
Thank you for your comment. The new module is so clearly. In the current, i focus to investigate a recommend feature to match with production data.

**Comment by mdekrey** [comment]
Since the MLData folder from the original sample is checked directly into the repository, please exercise caution with this PR. This data is very large and not using GitLFS (if merged, it would permanently increase the size required to clone SimplCommerce), and won't be useful to future users of SimplCommerce. If this continues to progress, deleting the data and issuing a "squash commit" would eliminate the vestigial data.

However, this does look like a great starting point for working on a recommendation engine. Maybe consider splitting the data loading and the data training to two separate services to be able to support running it off of the main web app? As it stands the web app used for SimplCommerce doesn't currently need to be a high compute instance.

**Comment by ainhattv** [comment]
@mdekrey You right,
In the case system have big data and cannot expand the server as monolithic.
With the current design, if we want the training time does not impact with runtime then we can choose another solution such as Azure ML Studio.
So, if we use Azure ML Studio as third party which idea may be change the main idea of current system, need to take care about that.
@thiennn Could you help me consider to use Azure ML Studio?

**Comment by afernandes** [comment]
I didn't have much free time, so I just put what already existed to work with real data.
Then I can convert the product recommendation project to a module and create a view component so that I don't have to modify the catalog module directly.

**Comment by afernandes** [comment]
To test, make some sales with more than one product then restart the application to train using the data (data.txt) or wait a day for the job to run again and train again.

**Pull request closed without merging**
