### PR TITLE
Updated AspNetCore 2.1.2->2.1.4

### PR DESCRIPTION
**Pull request by rafsanulhasan**
@thiennn in this PR I updated:
- [x] Infrastructure Project's NuGet Package `Microsoft.AspNetCore.App 2.1.2-> 2.1.4`
- [x] WebHost project's _NuGet Packages_:
   * `Microsoft.AspNetCore.App 2.1.2-> 2.1.4`
   * `Microsoft.EntityFrameworkCore.SqlServer 2.1.2->2.1.3`
   * `Microsoft.VisualStudio.Web.CodeGeneration.Design 2.1.3->2.1.4`
- [x] Test projects' _NuGet Packages_ `Microsoft.NET.Test.SDK 15.7.2->15.8.0`
- [x] Code for Small refactorings which fixes warning
- [x] Dockerfile to use: `Runtime 2.1.1->2.1.4`, `SDK 2.1->2.1.402`
- [x] All project files (.csproj) excluding `Infrastructure` to use specify `RuntimeFrameworkVersion` to `2.1.4`
- [x] [Readme.md](https://github.com/simplcommerce/SimplCommerce/edit/master/README.md): [Line 25](https://github.com/simplcommerce/SimplCommerce/edit/master/README.md#L25), [Line 41](https://github.com/simplcommerce/SimplCommerce/edit/master/README.md#L41), [Line 52](https://github.com/simplcommerce/SimplCommerce/edit/master/README.md#L52), [Line 53](https://github.com/simplcommerce/SimplCommerce/edit/master/README.md#L53), [Line 54](https://github.com/simplcommerce/SimplCommerce/edit/master/README.md#L54)
- [ ] Update E-Books

### CODE REVIEW

**Comment by rafsanulhasan** [comment]
@thiennn Please review

**Comment by thiennn** [comment]
I don't think adding <RuntimeFrameworkVersion>2.1.4</RuntimeFrameworkVersion> to every modules is a good idea. Please keep the PR focus, an PR should contain only changes need for 1 problem. The please also pay attention to indentation and spacing

**Comment by rafsanulhasan** [comment]
Should I remove version 2.1.4 like this from modules?

**Comment by thiennn** [comment]
Can you tell be the idea behind of adding `<RuntimeFrameworkVersion>2.1.4</RuntimeFrameworkVersion>` modules? What is the problem if we don't add it.

**Comment by hishamco** [comment]
Are we really need to update to `2.1.4` or should wait for `2.2` unless there 're bug(s) that need to be fixed in SimplCommerce

**Comment by thiennn** [comment]
@hishamco I think we should upgrade to 2.1.4. It's the LTS version.
@rafsanulhasan modules are actually the class libraries, only the WebHost actually the web app. Could you please help us remove in all the module <RuntimeFrameworkVersion>2.1.4</RuntimeFrameworkVersion>.

Btw, we are going to convert all the modules to Razor Class Library #422 .In case you want to add the same property for multiple projects, leverage the Directory.Build.props. https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

**Comment by hishamco** [comment]
> I think we should upgrade to 2.1.4. It's the LTS version

Is it a value for us?

**Comment by rafsanulhasan** [comment]
@hishamco  obviously
@thiennn okay. I've tested the RCL. it works fine and I have the full code that work with RCL. Waiting for you to accept this PR and after that I will make another PR with the RCL

**Comment by justindongqiang** [comment]
Hey I am getting following when getting the latest:

PM> update-database
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(Object reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DatabaseUpdateCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.
PM>

**Comment by rafsanulhasan** [comment]
@justindongqiang the latest update should work with `update-database` without any workaround if you have VS 2017 15.8.x installed since SQL Express is automatically installed upon VS installation process

**Comment by justindongqiang** [comment]
@rafsanulhasan thanks and maybe I need to install EF tool in VS.

**Comment by rafsanulhasan** [comment]
@justindongqiang EF is no more a VS scoped thing like it was before, it now have been moved as a 
 framework scoped thing in .NET Core 2.1. Because it is not packaged with `Microsoft.AspNetCore.App` meta package. Moreover, the tooling it needs to do **Reverse Engineering Code-First** approach for `database migrations` is now being shipped with the **.NET Core SDK** (`DOTNET.EXE`) itself and no need to specify the tooling NuGet package (`Microsoft.EntityFrameworkCore.Tools`) in the _project xml file_.

**Comment by justindongqiang** [comment]
The thing is if I change prof file to lower version 2.1.1 "Microsoft.AspNetCore.App" Version="2.1.1" />,then I run everything fine.

**Comment by rafsanulhasan** [comment]
@justindongqiang I think you need to install the latest version of [**.NET Core SDK 2.1.402**](https://www.microsoft.com/net/download/dotnet-core/2.1)

**Comment by thiennn** [comment]
A good pull request should contains a minimum changes for one problem. All the specific environment like connection string .. should not be included. 

I have make another pull request to upgrade to 2.1.4 #582 Fixing warning in InvariantDecimalModelBinderProvider.cs should be in another pull request.

Anyway, thank you for your effort

**Comment by justindongqiang** [comment]
@rafsanulhasan can we connect over skype? mine is justindong1

**Comment by rafsanulhasan** [comment]
obviously, my skype id is `rafsanulhasan`

**Pull request closed without merging**
