### PR TITLE
added unit test cases

### PR DESCRIPTION
**Pull request by Arunkumar0610**
added tests for  #1037 #1069 
**1. SimplCommerce.Module.Core**
                Services - WidgetInstanceService 
**2. SimplCommerce.Module.Pricing** 
                Controllers - CartRuleApiController & CartRuleUsageApiController
**3. SimplCommerce.Module.ProductComparison** 
                 Services - ComparingProductService  
                 Controllers - ComparingProductController
**4. SimplCommerce.Module.ShippingFree** 
                 Services- FreeShippingServiceProvider

### CODE REVIEW

**Comment by Arunkumar0610** [comment]
Hi @hishamco, I have raised the new PR for each test project.  #1069

**Comment by hishamco** [comment]
Why not small manageable PRs to make it easier to review

**Comment by Arunkumar0610** [comment]
Hi @hishamco , raised  new PR for each testproject

**Comment by hishamco** [comment]
I think this need to be closed

**Pull request closed without merging**
