### PR TITLE
Add BtcPayServer payment support (BTC, Lightning)

### PR DESCRIPTION
**Pull request by Kukks**
This PR introduces a new payment provider: BtcPayServer
BtcPayServer is a non-custodial, self-hosted & open source crypto payment processor.

### CODE REVIEW

**Comment by hishamco** [comment]
Why the builds are FAILED?

**Comment by Kukks** [comment]
Seems like master fails the tests

**Comment by thiennn** [comment]
Sorry @Kukks I didn't have time to look at your PR. Your code is fine. The ci build fail because the .net core sdk version of the global.json it out of date. I have fixed it on master branch. Could you please sync the latest master and resolve the conflict, then I can merge this PR.

Thanks

**Comment by thiennn** [comment]
The code cannot build because the db migration is added with PostgreSQL but the main stream in the code base is MS SQL,
But I don't have time to fix and I also don't know much about BtcPayServer, I don't know how to test.
So sorry that I cannot merge this PR.

**Pull request closed without merging**
