### PR TITLE
Use language switcher instead of _SelectLanguagePartial

### PR DESCRIPTION
**Pull request by hishamco**
Introducing `LanguageSwitcher` to SimplCommerce will many things in mind:

- Move localization UI components to `SimplCommerce.Module.Localization`
- Create a language selector with minimal amount of code, this will avoid creating `LocalizationController`
- Many enhancements can be done afterward such as display mode, so the tag helper will be able to display languages name, flags .. etc, using `TagHelperComponent` to inject the script that's necessary to append language switcher cookie

/cc @thiennn

### CODE REVIEW

**Comment by thiennn** [comment]
Sorry for the late response. I like the idea of moving localization UI components to SimplCommerce.Module.Localization. However I think using ViewComponent might better for this case because its View is separated, we can modify the UI or apply theme easier, the code also look cleaner I think

**Comment by hishamco** [comment]
@thiennn need a way to copy Components folder into the host, I think we need to do this at task build

**Comment by thiennn** [comment]
@hishamco No, I don't need to do anything to copy, all the views now are built into dll and copied automatically to the Host

**Comment by hishamco** [comment]
Precompiled views?!! if is that the `LanguageSwitcherViewComponent` is ready to ship 😄

**Comment by hishamco** [comment]
> Currently the culture setting is stored in Core_User.Culture column. But the updated code seems not update that value when user switch the culture

I didn't change the previous code too much, it's still use the same code, unless there's a change in the column that I didn't aware about!!

>Btw please resolve the conflict and clean up unused taghelper code

Strange!! I'm not sure why the TagHelper code is added here, perhaps it's my bad in the last commit, I will fetch the latest code and rebase

**Comment by hishamco** [comment]
@thiennn What's the status of this?

**Comment by hishamco** [comment]
@thiennn is there anything blocking this?

**Comment by hishamco** [comment]
@thiennn any update on this?

**Comment by hishamco** [comment]
I'm unhappy with the latest changes, perhaps i'm fine with the `async` one, because we reach the place from where we start

Could you please rid off use of controller and revert the latest changes except the `async` one

**Comment by thiennn** [comment]
The previous change doesn't work.

**Pull request closed without merging**
