### PR TITLE
Modules dependecies

### PR DESCRIPTION
**Pull request by hishamco**
This is WIP and I will rebase once PR #579 is merged, the idea as the following:

1. Upload the module package `{Module}.zip` into a `Temps` folder through admin section
2. Module installation process as the following:
     1. Ensure that module dependencies are already installed, this is simply by checking `modules.json`
     2. Module installation process will extract `{Module}.zip` to `Modules\{Module}` folder
     3. Remove the `{Module}.zip` from `Temps` folder
     4. Load the module assembly
3. Module uninstallation process as the following:
     1. Unload the module assembly
     2. Delete `Modules\{Module}` folder

We may install the module dependencies packages if we have sort of repository

/cc @thiennn

### CODE REVIEW

**Comment by hishamco** [comment]
As I mentioned above this a WIP, regarding your points

> Ordering the module list depends on dependencies

please refer to my previous comment

> Assets: javascript, css injection

> UI injection: menu, views

I think the views and assets will be there with the module, can you clarify the injection part?

> Database migration

This will be applied during a module installation

> CLI to package a module

This is optional, but we can do it in the future

> Webserver restarting

According to my assumption no restart is required


IMHO we can file an issue per prerequisite to simply the process

**Comment by afernandes** [comment]
Sort a list by a topological sorting, which consider their  dependencies.

https://www.codeproject.com/Articles/869059/Topological-sorting-in-Csharp

https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp/Collections/Extensions/ListExtensions.cs

**Comment by hishamco** [comment]
I need to revise this or split the PR if the changes are huge

**Comment by thiennn** [comment]
We need to rethink the approach for module management. 
This pr is kind of out of date, let close it. However, feel free to make change and reopen it

**Pull request closed without merging**
