### PR TITLE
Updated to .NET Core 1.1.1

### PR DESCRIPTION
**Pull request by MaherJendoubi**
Updated readme and references to 1.1.1

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
@thiennn please review

**Comment by thiennn** [comment]
@MaherJendoubi thank you, but I cannot checkout your changes to do some testing. Where is your original repository or branch? What I see in github is "simplcommerce:master from unknown repository"

**Comment by MaherJendoubi** [comment]
@thiennn I deleted the repo accidentally

**Comment by MaherJendoubi** [comment]
@thiennn  I need to close this one and I will send you later a new PR.

**Pull request closed without merging**
