### PR TITLE
Update to AspNetCore 3.1

### LINKED ISSUE #846: update net core 3.1
update net core 3.1

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #846 

/cc @thiennn

### CODE REVIEW

**Comment by thiennn** [comment]
please also update:
- azure-pipelines.yml
- travis.yml
- global.json
and the README.md

**Comment by hishamco** [comment]
Sure

**Comment by hishamco** [comment]
@thiennn ready to :shipit:

**Comment by thiennn** [comment]
Thanks

**Pull request merged**
