### PR TITLE
correct friendly url

### PR DESCRIPTION
**Pull request by YuriiPovkh**
Hi,
correct for #155

### CODE REVIEW

**Comment by thiennn** [comment]
Thank @YuriiPovkh But to be honest, I am not sure whether we should leave the Unicode characters in the URL or convert them to ASCII. Previously, I had tried to convert to ASCII, but it didn't work well in some languages.

**Comment by YuriiPovkh** [comment]
Sorry for delay,
It’s still Unicode with another normalization type, I can add any tests for any languages.

**Comment by thiennn** [comment]
I think we should add an option that allow users to configure how the urls look like (remove accents or not). For Vietnamese people like me, we want to remove all the accents, for example: "nhà nàng ở đâu" --> "nha-nang-o-dau", the current implement work perfectly this way but not for some other languages like Chinese or Russian

**Comment by thiennn** [comment]
#278

**Pull request closed without merging**
