### PR TITLE
Cache localization resources

### PR DESCRIPTION
**Pull request by hishamco**
This another part of issue #545 which includes:
- Cache the localization resources
- Load resources for a given culture on demand, which is extremely improve the performance

### CODE REVIEW

**Comment by thiennn** [comment]
Previously the all the resources are loaded one, at the startup time. This implement looks live resolved #553 ?

Just wondering, doesn't it work if we move the `services.AddCustomizedLocalization();` to the Localization module by creating an ModuleInitializer : IModuleInitializer

**Comment by hishamco** [comment]
Issue #553 filed for the translation in the admin

> Just wondering, doesn't it work if we move the services.AddCustomizedLocalization(); to the Localization module by creating an ModuleInitializer : IModuleInitializer

May be, but to make this align with other `AddCustomized` extension methods, so we can think about this later and doing it for all the modules

**Comment by thiennn** [comment]
Okay, thanks

**Pull request merged**
