### PR TITLE
Add boostrap star rating locale script automatically

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
This now fetch the locle script automatically even with culture hierarchy:

`ar`  -> `ar.js`
`ar-SA`  -> `ar.js`
`vi-VN` -> `vi-vn.js`
`en-US` -> Use the defaults

**Comment by thiennn** [comment]
Sorry but I prefer simplicity, and for better performance. If someone would like to run well in his own language, then he need to add the translation if it not exist.

**Comment by hishamco** [comment]
> Sorry but I prefer simplicity

For simplicity doing this automatically is a better choice instead of doing the same thing per culture

> for better performance

I don't know what is the perf impact here?!!

**Comment by thiennn** [comment]
The origin code is simpler and already load the locale for selected culture.
About performance, in the new code,  every request will do extra check to see weather the file exists on disk.

**Comment by hishamco** [comment]
> The origin code is simpler and already load the locale for selected culture.

The current code may raise 404 when the rating script is not supported for the current culture, but mine will ensure the existence of the script

> About performance, in the new code, every request will do extra check to see weather the file exists on disk.

You right, we can fix this by introduce a simple cache mechanism, so the check will be once per new culture

IMHO introducing the caching will resolve the issue for the current and the proposed solution

**Comment by thiennn** [comment]
If someone would like to run well in his own culture, then he need to add the translation if it not exist.

**Comment by hishamco** [comment]
Again the current implementation will raise 404 and it will not fallback to the parent culture, but the proposed technique has advantage that its avoid 404 and trying to fallback to the parent culture

At the end it's up to you to accept it or rejected after add caching :)

**Pull request closed without merging**
