### PR TITLE
 Implemented real-time notification with signalR and Hangfire.

### PR DESCRIPTION
**Pull request by Nongzhsh**
@thiennn Hi, i added the HangfireJobs module and Notifications module.
Please review it, then I will implement user notification management.
Looking forward to your reply.

### CODE REVIEW

**Comment by thiennn** [comment]
@Nongzhsh  sorry for the late response, I was super busy recently. There is too much code in this PR, it will take time to review :)

**Comment by Nongzhsh** [comment]
@thiennn Hi, I have synced the latest code and solved the conflict. Can you take a moment to check it? Thank you very much.

**Comment by thiennn** [comment]
@Nongzhsh  Can we move the RealTime folder in Core to a separate module? I think we should keep the Core module thin

**Comment by Nongzhsh** [comment]
@thiennn Okay, got it. We can refactor it.

**Comment by Nongzhsh** [comment]
We should handle the notifications events (send and received events) on the client. 

We can use https://github.com/bcerati/js-event-bus

**Comment by afernandes** [comment]
> We should handle the notifications events (send and received events) on the client.
> 
> We can use https://github.com/bcerati/js-event-bus

event bus basic

```html
<html>
<head>
    <script>
        var simplCommerce = simplCommerce || {};

        /* SIMPLE EVENT BUS *****************************************/

        simplCommerce.event = (function () {

            var _callbacks = {};

            var on = function (eventName, callback) {
                if (!_callbacks[eventName]) {
                    _callbacks[eventName] = [];
                }

                _callbacks[eventName].push(callback);
            };

            var off = function (eventName, callback) {
                var callbacks = _callbacks[eventName];
                if (!callbacks) {
                    return;
                }

                var index = -1;
                for (var i = 0; i < callbacks.length; i++) {
                    if (callbacks[i] === callback) {
                        index = i;
                        break;
                    }
                }

                if (index < 0) {
                    return;
                }

                _callbacks[eventName].splice(index, 1);
            };

            var trigger = function (eventName) {
                var callbacks = _callbacks[eventName];
                if (!callbacks || !callbacks.length) {
                    return;
                }

                var args = Array.prototype.slice.call(arguments, 1);
                for (var i = 0; i < callbacks.length; i++) {
                    callbacks[i].apply(this, args);
                }
            };

            // Public interface ///////////////////////////////////////////////////

            return {
                on: on,
                off: off,
                trigger: trigger
            };
        })();
    </script>
</head>
<body>

    <button id="btnTest" onclick="javascript:btnTest_click();">Test</button>

    <script>
        simplCommerce.event.on('simplCommerce.init', function (notification) {
            alert(notification);
        });

        simplCommerce.event.on('simplCommerce.init', function (notification) {
            alert(notification + ' ok');
        });

        var btnTest_click = function(){
           simplCommerce.event.trigger('simplCommerce.init', 'test 123');
        }
    </script>
</body>

</html>
```

**Pull request merged**
