### PR TITLE
simplified gulpfile and cleaned up package.json (#315)

### PR DESCRIPTION
**Pull request by iyilm4z**
**1-)** _del_ module is removed - _del_ and _rimraf_ were doing totally the same work and i preferred _rimraf_ coz it was also dependecy of _del_.
**2-)** _mPaths_ and _paths_ are mergered - ppl on the net were recommending the way i did.
**3-)** i realized some code lines in _copy-static_ and _copy-modules_ were the same. that's why i implied the prensible _DIY_. i called _copy-static_ task from _copy-modules_.
**4-)** i aslo did some _refactorig_ like changing the order of methods to make the code more readable.

**note:** i tested it many times on master branch and each time it worked properly. i hope u also think it's simplier now.

### CODE REVIEW

**Comment by thiennn** [comment]
The code looks nice. 
Could you please help me clean up the package.json also
Thanks

**Comment by iyilm4z** [comment]
@thiennn i  already did it! but i also want to make **bower.json** better coz these two files are related aslo **gulpfile.js**! but i need your help! how can i make sure which _bower packages_ we have dependecies? lemme tell you something strange, when i run "gulp clean:lib" i see four folders aren't deleted! i found two of them in bower's repo but for other two packages i donno what to do!  any recommendations? coz i want to make it like we clone our repo and run "npm install" after this comment i want to make bower packages(bower_components) downloaded and added to our **lib** folder and modules are copied! ony **one command** and all is ready!
pic

**Comment by thiennn** [comment]
Some lib don't have bower package. I have manually download and put them to the lib folder.  The tasks clean:lib,  copy-lib only affect on items declared in the bower object.
Some gulp tasks min, min:css, min:js aren't used at the moment.
Nowadays, people do not use bower any more. But I haven't figured out a better way to manage front-end packages.

**Comment by iyilm4z** [comment]
i think this project needs better html theme but anyway i made a commit for better package.json as you want, check it out please.

**Comment by thiennn** [comment]
Look good, thanks,
"i think this project needs better html theme" agree. It would be great if you can support on that

**Comment by iyilm4z** [comment]
@thiennn sorry but i forgot to change the task name "clean-module" to "clean-modules" in gulpfile. i used "gulp clean-modules" script in pachake.json but we still have "clean-module" in our gulpfile. it means this script couldnt be worked but it is not a big deal but we need to do it! the name "clean-modules" is also better for code-convention.

**Pull request merged**
