### PR TITLE
Send mail with Sendgrid

### PR DESCRIPTION
**Pull request by jducobu**

### CODE REVIEW

**Comment by Joy2BeWith** [comment]
SOMEONE BROKE THE BUILD....








Internal Server Error An unhandled exception occurred while processing the
request.
InvalidOperationException: A view component named 'SearchForm' could not be
found. A view component must be a public non-abstract class, not contain
any generic parameters, and either be decorated with
'ViewComponentAttribute' or have a class name ending with the
'ViewComponent' suffix. A view component must not be decorated with
'NonViewComponentAttribute'.

Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeAsync(string
name, object arguments)

   - Stack
   - Query
   - Cookies
   - Headers


   - InvalidOperationException: A view component named 'SearchForm' could
   not be found. A view component must be a public non-abstract class, not
   contain any generic parameters, and either be decorated with
   'ViewComponentAttribute' or have a class name ending with the
   'ViewComponent' suffix. A view component must not be decorated with
   'NonViewComponentAttribute'.
      - Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeAsync(string
      name, object arguments)
      - AspNetCore._Views_Shared__Layout_cshtml+<<ExecuteAsync>b__28_5>d.MoveNext()
      in _Layout.cshtml+
      1. </head>
         2. <body>
         3. <div class="top-bar">
         4. <div class="container">
         5. <ul class="list-inline list-unstyled pull-right">
         6. @await Html.PartialAsync("_SelectLanguagePartial")
      1. @await Html.PartialAsync("_LoginPartial")
      1. </ul>
         2. </div>
         3. </div>
         4. <div class="main-header">
         5. <div class="container">
         6. <div class="row">
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext+<SetOutputContentAsync>d__30.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      AspNetCore._Views_Shared__Layout_cshtml+<ExecuteAsync>d__28.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageCoreAsync>d__16.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageAsync>d__15.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderLayoutAsync>d__18.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderAsync>d__14.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__22.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__21.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext
      context)
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State
      next, ref Scope scope, ref object state, ref bool isCompleted)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext
      context)
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State
      next, ref Scope scope, ref object state, ref bool isCompleted)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by thiennn** [comment]
@Joy2BeWith Please make your the modules are copied correctly in your PC. Check out the doc here http://docs.simplcommerce.com/en/latest/development-tips/

**Comment by Joy2BeWith** [comment]
I deleted my local folder, cloned a new one, got latest, performed
update-database and STILL getting errors... this time:




Internal Server Error An unhandled exception occurred while processing the
request.
InvalidOperationException: Role GUEST does not exist.

Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore+<AddToRoleAsync>d__34.MoveNext()

   - Stack
   - Query
   - Cookies
   - Headers


   - InvalidOperationException: Role GUEST does not exist.
      -
      Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore+<AddToRoleAsync>d__34.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Identity.UserManager+<AddToRoleAsync>d__104.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      - System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      - SimplCommerce.Module.Core.Extensions.WorkContext+<GetCurrentUser>d__7.MoveNext()
      in WorkContext.cs+
      1. FullName = "Guest",
         2. UserGuid = userGuid.Value,
         3. Email = dummyEmail,
         4. UserName = dummyEmail
         5. };
         6. var abc = await _userManager.CreateAsync(_currentUser,
         "1qazZAQ!");
      1. await _userManager.AddToRoleAsync(_currentUser, "guest");
      1. SetUserGuidCookies(_currentUser.UserGuid);
         2. return _currentUser;
         3. }
         4.
         5. private Guid? GetUserGuidFromCookies()
         6. {
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      - System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      - SimplCommerce.Module.ShoppingCart.Components.CartBadgeViewComponent+<InvokeAsync>d__3.MoveNext()
      in CartBadgeViewComponent.cs+
      1. _cartService = cartService;
         2. _workContext = workContext;
         3. }
         4.
         5. public async Task<IViewComponentResult> InvokeAsync()
         6. {
      1. var currentUser = await _workContext.GetCurrentUser();
      1. var cart = await _cartService.GetCart(currentUser.Id);
         2. return
         View("/Modules/SimplCommerce.Module.ShoppingCart/Views/Components/CartBadge.cshtml",
         cart.Items.Count);
         3. }
         4. }
         5. }
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker+<InvokeAsyncCore>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker+<InvokeAsync>d__5.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper+<InvokeCoreAsync>d__12.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      - System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      - AspNetCore._Views_Shared__Layout_cshtml+<<ExecuteAsync>b__29_5>d.MoveNext()
      in _Layout.cshtml+
      1. </a>
         2. </div>
         3. <div class="col-xs-10 col-md-7 search-box">
         4. @await Component.InvokeAsync("SearchForm")
         5. </div>
         6. <div class="col-xs-2 col-md-1 cart-btn">
      1. @await Component.InvokeAsync("CartBadge")
      1. </div>
         2. </div>
         3. </div>
         4. </div>
         5. <div class="navbar navbar-default main-nav">
         6. <div class="container">
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext+<SetOutputContentAsync>d__30.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      AspNetCore._Views_Shared__Layout_cshtml+<ExecuteAsync>d__29.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageCoreAsync>d__16.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageAsync>d__15.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderLayoutAsync>d__18.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderAsync>d__14.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__22.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__21.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext
      context)
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State
      next, ref Scope scope, ref object state, ref bool isCompleted)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext
      context)
      - Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State
      next, ref Scope scope, ref object state, ref bool isCompleted)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__4.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      -
      Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
      - System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      - System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
      task)
      -
      Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by thiennn** [comment]
Hi @Joy2BeWith Update-Database only create database tables. The error you showed is the error when you run the application with insert predefined data. Please follow the instructions http://docs.simplcommerce.com/en/latest/getting-started/ by run the src/Database/StaticData.sql (you might need to delete all the existing records in the Core_User) to run this script

**Comment by Joy2BeWith** [comment]
regarding tax rates, will we be able to import tax tables? there are 1800
tax rates in California alone! thanks!

**Comment by thiennn** [comment]
Can you send the the file to import?

**Comment by Joy2BeWith** [comment]
Yes I’ll have my wife who is a cpa get me one to send you!

**Pull request merged**
