### PR TITLE
On SimplCommerce.Module.Cms replaced all manual mappings

### PR DESCRIPTION
**Pull request by YuriiPovkh**
Hi,
on SimplCommerce.Module.Cms replaced all manual mappings using AutoMapper

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
@YuriiPovkh Adding automapper is a great idea! Thank you.

**Comment by YuriiPovkh** [comment]
@MaherJendoubi
Thanks for your great opinion, 
I will replace all manual mappings on my feature pull requests.

**Comment by thiennn** [comment]
@YuriiPovkh , @MaherJendoubi 

I am struggling whether using AutoMapper is good or not in our project. Although it help reduce the number lines of code, however it introduces more magic, the code become harder to read, and we will loose the compiler type checking. We have to leverage the unit test to check the mapping. Normally our classes don't have much properties.

**Comment by MaherJendoubi** [comment]
@jbogard We need your feedback for this discussion. Thanks.

**Comment by YuriiPovkh** [comment]
@thiennn 
I think something like
```c#
var model = _mapper.Map<WidgetInstance, CarouselWidgetForm>(widgetInstance); 
```
better than
```c#
var model = new CarouselWidgetForm 
{ 
    Id = widgetInstance.Id, 
    Name = widgetInstance.Name, 
    WidgetZoneId = widgetInstance.WidgetZoneId, 
    PublishStart = widgetInstance.PublishStart, 
    PublishEnd = widgetInstance.PublishEnd, 
    Items = JsonConvert.DeserializeObject<IList<CarouselWidgetItemForm>>(widgetInstance.Data) 
}; 
```
I think that such manual mappings for us is very bad. AutoMapper is very simple to understending and use.  For me automapper make code more readable, and easier, we have many duplication on simple controller right now.

**Comment by thiennn** [comment]
@YuriiPovkh , Yes, with AutoMapper the code looks cleaner. However
```cs var model = _mapper.Map<WidgetInstance, CarouselWidgetForm>(widgetInstance); ``` 
The information is hidden, you don't know which properties the CarouselWidgetForm are populated without checking AutoMapper configuration. It might take sometime for people to find out where the mapping configuration is located. And if you rename a properties, the compiler cannot help. 

Still hesitating ...

**Comment by jbogard** [comment]
@MaherJendoubi sure, what feedback are you looking for?

Just some code feedback - you need a test that does `AssertConfigurationIsValid`. That's what checks to make sure all the properties are mapped and you haven't misspelled (or renamed) anything. I'd get rid of all those tests with one call to AssertConfigurationIsValid.

Second, your test initializes twice. You just need to call `Mapper.Initialize` once and if you want a mapper instance, you can pass through `Mapper.Instance` or create a new mapper like `new Mapper(Mapper.Configuration)`.

As for "is AutoMapper right for this project", that's really up to you. Lots of these tools can be seen as "magic" (DI, ORMs, JSON serializers etc.) so it's a comfort thing. I also don't know how big this project is/will be, so there's a conceptual cost for introducing these things on a smaller project.

**Comment by MaherJendoubi** [comment]
@jbogard Thanks a lot for this great feedback. @thiennn I understand that AutoMapper is useful for mapping complex objects. At this state of the project, the objects are simple but as soon as more and more features will be added to the project, these objects will more complex. I also understand that mapping manually the properties makes the project more debugguable but we can ensure the correctness of the mapping through unit tests.

**Comment by thiennn** [comment]
Thank you @jbogard, @YuriiPovkh , @MaherJendoubi 
In my opinion, I think AutoMapper is great if the objects have many properties to map.
In SimplCommerce, normally the classes don't have such a big number of properties. And to keep everything simple, I prefer manual mapping:
- It's explicit
- We don't need to write unit test for the mapping if we do it manually. The compiler will help us in case the properties is removed or changed. Manual mapping code < auto mapping code + custom mapping code + unit test code for mapping?
- No extra configuration needed. like 
```cs
_mapper.Map(model, widgetInstanceForModification, op => op.BeforeMap((fModel, tWidgetInstanceForModification) =>
     {
         fModel.Id = tWidgetInstanceForModification.Id;
     }));

CreateMap<CarouselWidgetForm, WidgetInstance>()
     .ForMember(w => w.Data, f => f.MapFrom(src => JsonConvert.SerializeObject(src.Items)));
```
- And finnally, we don't have to make change on the code base. Save effort for other things

**Comment by jbogard** [comment]
I assume that if you do manual mapping, you DO have to write tests for every individual map. Compiler won't tell you if you forgot a property, which is far more often in my experience than renames/misspellings. AutoMapper makes sure you don't miss anything with `AssertConfigurationIsValid` but we looked at it as "do I do manual mapping and 100s of tests, or auto-mapping and 1 test". If it's just a few properties, a few types and it's super obvious, then there's not much to gain. I look at AutoMapper when we have dozens or hundreds of "maps".

Also, the Before/AfterMap thing is something I try suuuuuuuuper hard to avoid. In fact, I don't think I have a single project that uses it. That definitely gets into the land of magic.

**Comment by thiennn** [comment]
Thank you for the effort. We might consider this later, but for now we would like to keep the current implementation.

**Pull request closed without merging**
