### PR TITLE
Ng1.6.6

### PR DESCRIPTION
**Pull request by MaherJendoubi**
1. Updated Angularjs to 1.6.6 through bower.json file

2. Updated Readme file with the new version of Angularjs

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
@thiennn Please review it. Thanks.

**Comment by thiennn** [comment]
Please run the "copy-lib" gulp task and also check in the changes in wwwroot/lib folder

**Comment by hishamco** [comment]
Are we really need this update?!!

**Comment by MaherJendoubi** [comment]
@hishamco Honestly, no. The current version of AngularJS now is 1.7.4 and it is easy to do the update using LibMan.

**Comment by hishamco** [comment]
I made my comment because I saw two PRs for updating packages, but i'm asking if there's a need, because we can do such things in a regular basis

**Comment by MaherJendoubi** [comment]
The idea was to upgrade from AngularJS to Angular. That's why I keep up bumping the AngularJS version. But there is a cost for such upgrade since all the admin site of SimplCommerce is done with AngularJS.

**Comment by hishamco** [comment]
I see .. thanks for your clarification, but i'm asking why we 're using AngularJS fro admin section instead of MVC or Razor Pages?

**Comment by thiennn** [comment]
For the admin site which have a lot of data grid, form, interaction. Using a SPA framework can offer richer user experience, and also easier to implement when compare with transitional full page post back like MVC or Razor Pages. 

2 years ago, at the time I started SimplCommerce, Angular 2 hasn't been mature yet. So I decided to go with AngularJS. 

Although AngularJS now is considered legacy, it is still working as expected. It's simple and fit with the modular architecture of SimplCommerce.

We don't have effort to upgrade it. I think we should keep it as it is. Maybe 1 or 2 years later, Blazor or something excellent. We might re-write the admin site front-end.

Btw, I think we should close this PR. We should keep it as it is. Upgrading this will take a lot of effort to test

**Comment by hishamco** [comment]
IMHO rebuild the admin using Razor Pages will be a plus, so no need to create controller for views and APIs for Angular, regarding the postback we can solve it using AJAX, anyhow the UI is an important piece and we can create an issue discussing the alternatives, pros & cons

**Pull request closed without merging**
